#日志默认配置
logging:
  level:
    root: info
    org.springframework.boot.autoconfigure: info
    com.earth: debug
  register-shutdown-hook: true

server:
  port: 8880

feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000
        loggerLevel: full

spring:
  profiles:
    active: dev
  application:
    name: message-provider
  datasource:
    dbcp2:
      url: jdbc:mysql://rm-8vb3ubhv8jv0lqtrxeo.mysql.zhangbei.rds.aliyuncs.com:3306/dw
      username: sportsgw
      password: Sportsgw2019
      driver-class-name: com.mysql.cj.jdbc.Driver



  data:
    elasticsearch:
      cluster-name: elasticsearch_zhuoli
      cluster-nodes: 127.0.0.1:9300

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: earth
    password: earthpass
    publisher-confirms: true
    publisher-returns: true

  zookeeper:
    #每次重试时间间隔，单位毫秒
    baseSleepTimeMs: 1000
    #重试次数
    maxRetries: 3
    #zookeeper服务连接id与端口
    connectString: 127.0.0.1:2181
    #会话超时时间，单位毫秒
    sessionTimeoutMs: 5000
    #连接创建超时时间，单位毫秒
    connection-timeout-ms: 5000

earth-order-service: localhost:8081

mybatis:
  configuration:
    aggressive-lazy-loading: true

