#日志默认配置
logging:
  level:
    root: info
    com.zhuo: debug
  register-shutdown-hook: true
  file: message-provider
  path: /var/log/message-provider
server:
  port: 8080



spring:
  profiles:
    active: dev
  application:
    name: message-provider
  datasource:
    dbcp2:
      url: jdbc:mysql://localhost:3306/DW
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver



  data:
    elasticsearch:
      cluster-name: elasticsearch_zhuoli
      cluster-nodes: 127.0.0.1:9300

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: zhuoli
    password: zhuoli
    publisher-confirms: true
    publisher-returns: true